### ISSUE TITLE
Usage of Dynamic libraries to avoid linking libraries that are not neeeded

### ISSUE THREAD

**Issue by varsameer** [yahoo/NetCHASM#2]
If the current code can be modified to make use of Dynamic libraries for instantiation of derived class objects instead of concrete instantiation as is done currently during initialization from the master config, inclusion of unwanted libraries in the final binary can be avoided when developers have their own implementation of the derived classes . For example :- inclusion of MDBM library can be avoided when developers have their own implementation of the storage base class that makes use of a different backend database.

**Comment by juen1jp** [comment]
Decided to go with CMake variables to exclude unneeded libraries.
